#include <algorithm>
#include <iostream>
#include "TTree.h"
#include "TChain.h"
#include "include/BranchInit.h"
#include "include/BranchDefs.h"

namespace IN {
 Int_t				nVtxBS;
 Float_t				pfMET;
 Float_t				pfMETPhi;
 Float_t				pfMETsumEt;
 Float_t				pfMETmEtSig;
 Float_t				pfMETSig;
 Float_t				recoPfMET;
 Float_t				recoPfMETPhi;
 Float_t				recoPfMETsumEt;
 Float_t				recoPfMETmEtSig;
 Float_t				recoPfMETSig;
 Int_t				el_n;
 Int_t				mu_n;
 Int_t				ph_n;
 Int_t				jet_n;
 Int_t				vtx_n;
 std::vector<float>				*el_pt;
 std::vector<float>				*el_eta;
 std::vector<float>				*el_sceta;
 std::vector<float>				*el_phi;
 std::vector<float>				*el_e;
 std::vector<float>				*el_mva;
 std::vector<float>				*el_d0pv;
 std::vector<float>				*el_z0pv;
 std::vector<float>				*el_sigmaIEIE;
 std::vector<float>				*el_pfiso30;
 std::vector<bool>				*el_hasMatchedConv;
 std::vector<bool>				*el_passTight;
 std::vector<bool>				*el_passMedium;
 std::vector<bool>				*el_passLoose;
 std::vector<bool>				*el_passVeryLoose;
 std::vector<bool>				*el_passTightTrig;
 std::vector<bool>				*el_truthMatch_ph;
 std::vector<bool>				*el_truthMatch;
 std::vector<float>				*el_truthMinDR;
 std::vector<float>				*mu_pt;
 std::vector<float>				*mu_eta;
 std::vector<float>				*mu_phi;
 std::vector<float>				*mu_e;
 std::vector<float>				*mu_pfIso_ch;
 std::vector<float>				*mu_pfIso_nh;
 std::vector<float>				*mu_pfIso_pho;
 std::vector<float>				*mu_pfIso_pu;
 std::vector<float>				*mu_corrIso;
 std::vector<bool>				*mu_truthMatch;
 std::vector<float>				*mu_truthMinDR;
 std::vector<float>				*ph_pt;
 std::vector<float>				*ph_eta;
 std::vector<float>				*ph_phi;
 std::vector<float>				*ph_e;
 std::vector<float>				*ph_HoverE;
 std::vector<float>				*ph_sigmaIEIE;
 std::vector<float>				*ph_chIsoCorr;
 std::vector<float>				*ph_neuIsoCorr;
 std::vector<float>				*ph_phoIsoCorr;
 std::vector<bool>				*ph_isConv;
 std::vector<int>				*ph_conv_nTrk;
 std::vector<float>				*ph_conv_vtx_x;
 std::vector<float>				*ph_conv_vtx_y;
 std::vector<float>				*ph_conv_vtx_z;
 std::vector<float>				*ph_conv_ptin1;
 std::vector<float>				*ph_conv_ptin2;
 std::vector<float>				*ph_conv_ptout1;
 std::vector<float>				*ph_conv_ptout2;
 std::vector<bool>				*ph_passTight;
 std::vector<bool>				*ph_passMedium;
 std::vector<bool>				*ph_passLoose;
 std::vector<float>				*jet_pt;
 std::vector<float>				*jet_eta;
 std::vector<float>				*jet_phi;
 std::vector<float>				*jet_e;
 Float_t				avgPU;
 Bool_t				isBlinded;
 Float_t				m_leplepZ;
 Float_t				m_3lep;
 Float_t				m_4lep;
};
namespace OUT {
 Int_t				nVtxBS;
 Float_t				pfMET;
 Float_t				pfMETPhi;
 Float_t				pfMETsumEt;
 Float_t				pfMETmEtSig;
 Float_t				pfMETSig;
 Float_t				recoPfMET;
 Float_t				recoPfMETPhi;
 Float_t				recoPfMETsumEt;
 Float_t				recoPfMETmEtSig;
 Float_t				recoPfMETSig;
 Int_t				el_n;
 Int_t				mu_n;
 Int_t				ph_n;
 Int_t				jet_n;
 Int_t				vtx_n;
 std::vector<float>				*el_pt;
 std::vector<float>				*el_eta;
 std::vector<float>				*el_sceta;
 std::vector<float>				*el_phi;
 std::vector<float>				*el_e;
 std::vector<float>				*el_mva;
 std::vector<float>				*el_d0pv;
 std::vector<float>				*el_z0pv;
 std::vector<float>				*el_sigmaIEIE;
 std::vector<float>				*el_pfiso30;
 std::vector<bool>				*el_hasMatchedConv;
 std::vector<bool>				*el_passTight;
 std::vector<bool>				*el_passMedium;
 std::vector<bool>				*el_passLoose;
 std::vector<bool>				*el_passVeryLoose;
 std::vector<bool>				*el_passTightTrig;
 std::vector<bool>				*el_truthMatch_ph;
 std::vector<bool>				*el_truthMatch;
 std::vector<float>				*el_truthMinDR;
 std::vector<float>				*mu_pt;
 std::vector<float>				*mu_eta;
 std::vector<float>				*mu_phi;
 std::vector<float>				*mu_e;
 std::vector<float>				*mu_pfIso_ch;
 std::vector<float>				*mu_pfIso_nh;
 std::vector<float>				*mu_pfIso_pho;
 std::vector<float>				*mu_pfIso_pu;
 std::vector<float>				*mu_corrIso;
 std::vector<bool>				*mu_truthMatch;
 std::vector<float>				*mu_truthMinDR;
 std::vector<float>				*ph_pt;
 std::vector<float>				*ph_eta;
 std::vector<float>				*ph_phi;
 std::vector<float>				*ph_e;
 std::vector<float>				*ph_HoverE;
 std::vector<float>				*ph_sigmaIEIE;
 std::vector<float>				*ph_chIsoCorr;
 std::vector<float>				*ph_neuIsoCorr;
 std::vector<float>				*ph_phoIsoCorr;
 std::vector<bool>				*ph_isConv;
 std::vector<int>				*ph_conv_nTrk;
 std::vector<float>				*ph_conv_vtx_x;
 std::vector<float>				*ph_conv_vtx_y;
 std::vector<float>				*ph_conv_vtx_z;
 std::vector<float>				*ph_conv_ptin1;
 std::vector<float>				*ph_conv_ptin2;
 std::vector<float>				*ph_conv_ptout1;
 std::vector<float>				*ph_conv_ptout2;
 std::vector<bool>				*ph_passTight;
 std::vector<bool>				*ph_passMedium;
 std::vector<bool>				*ph_passLoose;
 std::vector<float>				*jet_pt;
 std::vector<float>				*jet_eta;
 std::vector<float>				*jet_phi;
 std::vector<float>				*jet_e;
 Float_t				avgPU;
 Bool_t				isBlinded;
 Float_t				m_leplepZ;
 Float_t				m_3lep;
 Float_t				m_4lep;
};
void InitINTree( TChain * tree) {

  tree->SetBranchAddress("nVtxBS", &IN::nVtxBS);
  tree->SetBranchAddress("pfMET", &IN::pfMET);
  tree->SetBranchAddress("pfMETPhi", &IN::pfMETPhi);
  tree->SetBranchAddress("pfMETsumEt", &IN::pfMETsumEt);
  tree->SetBranchAddress("pfMETmEtSig", &IN::pfMETmEtSig);
  tree->SetBranchAddress("pfMETSig", &IN::pfMETSig);
  tree->SetBranchAddress("recoPfMET", &IN::recoPfMET);
  tree->SetBranchAddress("recoPfMETPhi", &IN::recoPfMETPhi);
  tree->SetBranchAddress("recoPfMETsumEt", &IN::recoPfMETsumEt);
  tree->SetBranchAddress("recoPfMETmEtSig", &IN::recoPfMETmEtSig);
  tree->SetBranchAddress("recoPfMETSig", &IN::recoPfMETSig);
  tree->SetBranchAddress("el_n", &IN::el_n);
  tree->SetBranchAddress("mu_n", &IN::mu_n);
  tree->SetBranchAddress("ph_n", &IN::ph_n);
  tree->SetBranchAddress("jet_n", &IN::jet_n);
  tree->SetBranchAddress("vtx_n", &IN::vtx_n);
  tree->SetBranchAddress("el_pt", &IN::el_pt);
  tree->SetBranchAddress("el_eta", &IN::el_eta);
  tree->SetBranchAddress("el_sceta", &IN::el_sceta);
  tree->SetBranchAddress("el_phi", &IN::el_phi);
  tree->SetBranchAddress("el_e", &IN::el_e);
  tree->SetBranchAddress("el_mva", &IN::el_mva);
  tree->SetBranchAddress("el_d0pv", &IN::el_d0pv);
  tree->SetBranchAddress("el_z0pv", &IN::el_z0pv);
  tree->SetBranchAddress("el_sigmaIEIE", &IN::el_sigmaIEIE);
  tree->SetBranchAddress("el_pfiso30", &IN::el_pfiso30);
  tree->SetBranchAddress("el_hasMatchedConv", &IN::el_hasMatchedConv);
  tree->SetBranchAddress("el_passTight", &IN::el_passTight);
  tree->SetBranchAddress("el_passMedium", &IN::el_passMedium);
  tree->SetBranchAddress("el_passLoose", &IN::el_passLoose);
  tree->SetBranchAddress("el_passVeryLoose", &IN::el_passVeryLoose);
  tree->SetBranchAddress("el_passTightTrig", &IN::el_passTightTrig);
  tree->SetBranchAddress("el_truthMatch_ph", &IN::el_truthMatch_ph);
  tree->SetBranchAddress("el_truthMatch", &IN::el_truthMatch);
  tree->SetBranchAddress("el_truthMinDR", &IN::el_truthMinDR);
  tree->SetBranchAddress("mu_pt", &IN::mu_pt);
  tree->SetBranchAddress("mu_eta", &IN::mu_eta);
  tree->SetBranchAddress("mu_phi", &IN::mu_phi);
  tree->SetBranchAddress("mu_e", &IN::mu_e);
  tree->SetBranchAddress("mu_pfIso_ch", &IN::mu_pfIso_ch);
  tree->SetBranchAddress("mu_pfIso_nh", &IN::mu_pfIso_nh);
  tree->SetBranchAddress("mu_pfIso_pho", &IN::mu_pfIso_pho);
  tree->SetBranchAddress("mu_pfIso_pu", &IN::mu_pfIso_pu);
  tree->SetBranchAddress("mu_corrIso", &IN::mu_corrIso);
  tree->SetBranchAddress("mu_truthMatch", &IN::mu_truthMatch);
  tree->SetBranchAddress("mu_truthMinDR", &IN::mu_truthMinDR);
  tree->SetBranchAddress("ph_pt", &IN::ph_pt);
  tree->SetBranchAddress("ph_eta", &IN::ph_eta);
  tree->SetBranchAddress("ph_phi", &IN::ph_phi);
  tree->SetBranchAddress("ph_e", &IN::ph_e);
  tree->SetBranchAddress("ph_HoverE", &IN::ph_HoverE);
  tree->SetBranchAddress("ph_sigmaIEIE", &IN::ph_sigmaIEIE);
  tree->SetBranchAddress("ph_chIsoCorr", &IN::ph_chIsoCorr);
  tree->SetBranchAddress("ph_neuIsoCorr", &IN::ph_neuIsoCorr);
  tree->SetBranchAddress("ph_phoIsoCorr", &IN::ph_phoIsoCorr);
  tree->SetBranchAddress("ph_isConv", &IN::ph_isConv);
  tree->SetBranchAddress("ph_conv_nTrk", &IN::ph_conv_nTrk);
  tree->SetBranchAddress("ph_conv_vtx_x", &IN::ph_conv_vtx_x);
  tree->SetBranchAddress("ph_conv_vtx_y", &IN::ph_conv_vtx_y);
  tree->SetBranchAddress("ph_conv_vtx_z", &IN::ph_conv_vtx_z);
  tree->SetBranchAddress("ph_conv_ptin1", &IN::ph_conv_ptin1);
  tree->SetBranchAddress("ph_conv_ptin2", &IN::ph_conv_ptin2);
  tree->SetBranchAddress("ph_conv_ptout1", &IN::ph_conv_ptout1);
  tree->SetBranchAddress("ph_conv_ptout2", &IN::ph_conv_ptout2);
  tree->SetBranchAddress("ph_passTight", &IN::ph_passTight);
  tree->SetBranchAddress("ph_passMedium", &IN::ph_passMedium);
  tree->SetBranchAddress("ph_passLoose", &IN::ph_passLoose);
  tree->SetBranchAddress("jet_pt", &IN::jet_pt);
  tree->SetBranchAddress("jet_eta", &IN::jet_eta);
  tree->SetBranchAddress("jet_phi", &IN::jet_phi);
  tree->SetBranchAddress("jet_e", &IN::jet_e);
  tree->SetBranchAddress("avgPU", &IN::avgPU);
  tree->SetBranchAddress("isBlinded", &IN::isBlinded);
  tree->SetBranchAddress("m_leplepZ", &IN::m_leplepZ);
  tree->SetBranchAddress("m_3lep", &IN::m_3lep);
  tree->SetBranchAddress("m_4lep", &IN::m_4lep);
};

void InitOUTTree( TTree * tree ) {
  tree->Branch("nVtxBS", &OUT::nVtxBS, "nVtxBS/I");
  tree->Branch("pfMET", &OUT::pfMET, "pfMET/F");
  tree->Branch("pfMETPhi", &OUT::pfMETPhi, "pfMETPhi/F");
  tree->Branch("pfMETsumEt", &OUT::pfMETsumEt, "pfMETsumEt/F");
  tree->Branch("pfMETmEtSig", &OUT::pfMETmEtSig, "pfMETmEtSig/F");
  tree->Branch("pfMETSig", &OUT::pfMETSig, "pfMETSig/F");
  tree->Branch("recoPfMET", &OUT::recoPfMET, "recoPfMET/F");
  tree->Branch("recoPfMETPhi", &OUT::recoPfMETPhi, "recoPfMETPhi/F");
  tree->Branch("recoPfMETsumEt", &OUT::recoPfMETsumEt, "recoPfMETsumEt/F");
  tree->Branch("recoPfMETmEtSig", &OUT::recoPfMETmEtSig, "recoPfMETmEtSig/F");
  tree->Branch("recoPfMETSig", &OUT::recoPfMETSig, "recoPfMETSig/F");
  tree->Branch("el_n", &OUT::el_n, "el_n/I");
  tree->Branch("mu_n", &OUT::mu_n, "mu_n/I");
  tree->Branch("ph_n", &OUT::ph_n, "ph_n/I");
  tree->Branch("jet_n", &OUT::jet_n, "jet_n/I");
  tree->Branch("vtx_n", &OUT::vtx_n, "vtx_n/I");
  tree->Branch("el_pt", &OUT::el_pt);
  tree->Branch("el_eta", &OUT::el_eta);
  tree->Branch("el_sceta", &OUT::el_sceta);
  tree->Branch("el_phi", &OUT::el_phi);
  tree->Branch("el_e", &OUT::el_e);
  tree->Branch("el_mva", &OUT::el_mva);
  tree->Branch("el_d0pv", &OUT::el_d0pv);
  tree->Branch("el_z0pv", &OUT::el_z0pv);
  tree->Branch("el_sigmaIEIE", &OUT::el_sigmaIEIE);
  tree->Branch("el_pfiso30", &OUT::el_pfiso30);
  tree->Branch("el_hasMatchedConv", &OUT::el_hasMatchedConv);
  tree->Branch("el_passTight", &OUT::el_passTight);
  tree->Branch("el_passMedium", &OUT::el_passMedium);
  tree->Branch("el_passLoose", &OUT::el_passLoose);
  tree->Branch("el_passVeryLoose", &OUT::el_passVeryLoose);
  tree->Branch("el_passTightTrig", &OUT::el_passTightTrig);
  tree->Branch("el_truthMatch_ph", &OUT::el_truthMatch_ph);
  tree->Branch("el_truthMatch", &OUT::el_truthMatch);
  tree->Branch("el_truthMinDR", &OUT::el_truthMinDR);
  tree->Branch("mu_pt", &OUT::mu_pt);
  tree->Branch("mu_eta", &OUT::mu_eta);
  tree->Branch("mu_phi", &OUT::mu_phi);
  tree->Branch("mu_e", &OUT::mu_e);
  tree->Branch("mu_pfIso_ch", &OUT::mu_pfIso_ch);
  tree->Branch("mu_pfIso_nh", &OUT::mu_pfIso_nh);
  tree->Branch("mu_pfIso_pho", &OUT::mu_pfIso_pho);
  tree->Branch("mu_pfIso_pu", &OUT::mu_pfIso_pu);
  tree->Branch("mu_corrIso", &OUT::mu_corrIso);
  tree->Branch("mu_truthMatch", &OUT::mu_truthMatch);
  tree->Branch("mu_truthMinDR", &OUT::mu_truthMinDR);
  tree->Branch("ph_pt", &OUT::ph_pt);
  tree->Branch("ph_eta", &OUT::ph_eta);
  tree->Branch("ph_phi", &OUT::ph_phi);
  tree->Branch("ph_e", &OUT::ph_e);
  tree->Branch("ph_HoverE", &OUT::ph_HoverE);
  tree->Branch("ph_sigmaIEIE", &OUT::ph_sigmaIEIE);
  tree->Branch("ph_chIsoCorr", &OUT::ph_chIsoCorr);
  tree->Branch("ph_neuIsoCorr", &OUT::ph_neuIsoCorr);
  tree->Branch("ph_phoIsoCorr", &OUT::ph_phoIsoCorr);
  tree->Branch("ph_isConv", &OUT::ph_isConv);
  tree->Branch("ph_conv_nTrk", &OUT::ph_conv_nTrk);
  tree->Branch("ph_conv_vtx_x", &OUT::ph_conv_vtx_x);
  tree->Branch("ph_conv_vtx_y", &OUT::ph_conv_vtx_y);
  tree->Branch("ph_conv_vtx_z", &OUT::ph_conv_vtx_z);
  tree->Branch("ph_conv_ptin1", &OUT::ph_conv_ptin1);
  tree->Branch("ph_conv_ptin2", &OUT::ph_conv_ptin2);
  tree->Branch("ph_conv_ptout1", &OUT::ph_conv_ptout1);
  tree->Branch("ph_conv_ptout2", &OUT::ph_conv_ptout2);
  tree->Branch("ph_passTight", &OUT::ph_passTight);
  tree->Branch("ph_passMedium", &OUT::ph_passMedium);
  tree->Branch("ph_passLoose", &OUT::ph_passLoose);
  tree->Branch("jet_pt", &OUT::jet_pt);
  tree->Branch("jet_eta", &OUT::jet_eta);
  tree->Branch("jet_phi", &OUT::jet_phi);
  tree->Branch("jet_e", &OUT::jet_e);
  tree->Branch("avgPU", &OUT::avgPU, "avgPU/F");
  tree->Branch("isBlinded", &OUT::isBlinded, "isBlinded/O");
  tree->Branch("m_leplepZ", &OUT::m_leplepZ, "m_leplepZ/F");
  tree->Branch("m_3lep", &OUT::m_3lep, "m_3lep/F");
  tree->Branch("m_4lep", &OUT::m_4lep, "m_4lep/F");
}
void CopyInputVarsToOutput() {
  OUT::nVtxBS = IN::nVtxBS;
  OUT::pfMET = IN::pfMET;
  OUT::pfMETPhi = IN::pfMETPhi;
  OUT::pfMETsumEt = IN::pfMETsumEt;
  OUT::pfMETmEtSig = IN::pfMETmEtSig;
  OUT::pfMETSig = IN::pfMETSig;
  OUT::recoPfMET = IN::recoPfMET;
  OUT::recoPfMETPhi = IN::recoPfMETPhi;
  OUT::recoPfMETsumEt = IN::recoPfMETsumEt;
  OUT::recoPfMETmEtSig = IN::recoPfMETmEtSig;
  OUT::recoPfMETSig = IN::recoPfMETSig;
  OUT::el_n = IN::el_n;
  OUT::mu_n = IN::mu_n;
  OUT::ph_n = IN::ph_n;
  OUT::jet_n = IN::jet_n;
  OUT::vtx_n = IN::vtx_n;
  OUT::el_pt = IN::el_pt;
  OUT::el_eta = IN::el_eta;
  OUT::el_sceta = IN::el_sceta;
  OUT::el_phi = IN::el_phi;
  OUT::el_e = IN::el_e;
  OUT::el_mva = IN::el_mva;
  OUT::el_d0pv = IN::el_d0pv;
  OUT::el_z0pv = IN::el_z0pv;
  OUT::el_sigmaIEIE = IN::el_sigmaIEIE;
  OUT::el_pfiso30 = IN::el_pfiso30;
  OUT::el_hasMatchedConv = IN::el_hasMatchedConv;
  OUT::el_passTight = IN::el_passTight;
  OUT::el_passMedium = IN::el_passMedium;
  OUT::el_passLoose = IN::el_passLoose;
  OUT::el_passVeryLoose = IN::el_passVeryLoose;
  OUT::el_passTightTrig = IN::el_passTightTrig;
  OUT::el_truthMatch_ph = IN::el_truthMatch_ph;
  OUT::el_truthMatch = IN::el_truthMatch;
  OUT::el_truthMinDR = IN::el_truthMinDR;
  OUT::mu_pt = IN::mu_pt;
  OUT::mu_eta = IN::mu_eta;
  OUT::mu_phi = IN::mu_phi;
  OUT::mu_e = IN::mu_e;
  OUT::mu_pfIso_ch = IN::mu_pfIso_ch;
  OUT::mu_pfIso_nh = IN::mu_pfIso_nh;
  OUT::mu_pfIso_pho = IN::mu_pfIso_pho;
  OUT::mu_pfIso_pu = IN::mu_pfIso_pu;
  OUT::mu_corrIso = IN::mu_corrIso;
  OUT::mu_truthMatch = IN::mu_truthMatch;
  OUT::mu_truthMinDR = IN::mu_truthMinDR;
  OUT::ph_pt = IN::ph_pt;
  OUT::ph_eta = IN::ph_eta;
  OUT::ph_phi = IN::ph_phi;
  OUT::ph_e = IN::ph_e;
  OUT::ph_HoverE = IN::ph_HoverE;
  OUT::ph_sigmaIEIE = IN::ph_sigmaIEIE;
  OUT::ph_chIsoCorr = IN::ph_chIsoCorr;
  OUT::ph_neuIsoCorr = IN::ph_neuIsoCorr;
  OUT::ph_phoIsoCorr = IN::ph_phoIsoCorr;
  OUT::ph_isConv = IN::ph_isConv;
  OUT::ph_conv_nTrk = IN::ph_conv_nTrk;
  OUT::ph_conv_vtx_x = IN::ph_conv_vtx_x;
  OUT::ph_conv_vtx_y = IN::ph_conv_vtx_y;
  OUT::ph_conv_vtx_z = IN::ph_conv_vtx_z;
  OUT::ph_conv_ptin1 = IN::ph_conv_ptin1;
  OUT::ph_conv_ptin2 = IN::ph_conv_ptin2;
  OUT::ph_conv_ptout1 = IN::ph_conv_ptout1;
  OUT::ph_conv_ptout2 = IN::ph_conv_ptout2;
  OUT::ph_passTight = IN::ph_passTight;
  OUT::ph_passMedium = IN::ph_passMedium;
  OUT::ph_passLoose = IN::ph_passLoose;
  OUT::jet_pt = IN::jet_pt;
  OUT::jet_eta = IN::jet_eta;
  OUT::jet_phi = IN::jet_phi;
  OUT::jet_e = IN::jet_e;
  OUT::avgPU = IN::avgPU;
  OUT::isBlinded = IN::isBlinded;
  OUT::m_leplepZ = IN::m_leplepZ;
  OUT::m_3lep = IN::m_3lep;
  OUT::m_4lep = IN::m_4lep;
}
